spring:
  application:
    name: loan-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    openfeign:
      micrometer:
        enabled: true

server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8003/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

resilience4j:
  circuitbreaker:
    instances:
      creditScoreCB:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
  retry:
    configs:
      default:
        max-attempts: 5
        wait-duration: 5s
    instances:
      creditScoreCB:
        retry-exceptions:
          - feign.RetryableException
          - feign.FeignException
          - java.io.IOException
          - java.net.ConnectException
        base-config: default
        max-retry-attempts: 5
        wait-duration: 5s

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"